<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9uGTvOm\srcChallenge_App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9uGTvOm/srcChallenge_App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container9uGTvOm.legacy');

    return;
}

if (!\class_exists(srcChallenge_App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container9uGTvOm\srcChallenge_App_KernelTestDebugContainer::class, srcChallenge_App_KernelTestDebugContainer::class, false);
}

return new \Container9uGTvOm\srcChallenge_App_KernelTestDebugContainer([
    'container.build_hash' => '9uGTvOm',
    'container.build_id' => '61c6db9c',
    'container.build_time' => 1610385283,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9uGTvOm');
