status_get:
    path: /status
    controller: Challenge\App\Controller\HealthCheck\StatusGetController
    methods:  [GET]

user_onboard_post:
    path: /user/onboard
    controller: Challenge\App\Controller\Onboarding\OnBoardingPostController
    methods:  [POST]
